name: Datazip Cloud Build and Releaser (stable)
on:
  push:
    tags:
      - "driver-*/v*"
      - "adapter-*/v*"

jobs:
  build:
    name: Docker build and push
    env:
      RELEASE_CHANNEL: "stable"
      DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DHID: ${{ secrets.DOCKER_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run Release tool
        run: |
          chmod +x ./release-tool.sh
          ./release-tool.sh
        shell: bash
