name: Connector Build and Release (edge)

on:
  workflow_dispatch:
    inputs:
      connector:
        description: "Connector to build"

jobs:
  publish_connectors:
    name: Publish connector ${{ github.event.inputs.connector }} [manual]
    environment: Publish Connector
    runs-on: ubuntu-latest
    env:
      RELEASE_CHANNEL: "edge"
      DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DHID: ${{ secrets.DOCKER_USERNAME }}
      argument: ${{ github.event.inputs.connector }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: show git branch
        run: git branch --show-current
      - name: Set VERSION
        run: echo "VERSION=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV
      - name: show VERSION
        run: echo $VERSION
      - name: Run Release tool
        run: |
          chmod +x ./release-tool.sh
          ./release-tool.sh
        shell: bash
